name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade Cython==0.29.33 buildozer

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Қабули худкори ҳамаи шартномаҳои Android SDK
          mkdir -p ~/.android && touch ~/.android/repositories.cfg
          yes | buildozer android debug || true
          # Агар бори аввал хато диҳад, кӯшиш мекунем шартномаҳоро бо SDKManager тасдиқ кунем
          if [ ! -d "$HOME/.buildozer/android/platform/android-sdk" ]; then
            buildozer android debug --only-sdk-install || true
          fi
          yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true
          # Оғози сохтмони асосӣ
          buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "yes"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-first-app-apk
          path: bin/*.apk
